Feature/SCORING-1 Question Bank Automation 1.1
function-future/function-backend-qa pull request #46
Opened 2019-09-16 06:51 UTC by oliverrsebastian

#45  1. Create Question Bank

2019-09-16 07:19 UTC, jonathan016 requested changes

2019-09-16 07:19 UTC, jonathan016 commented on src/test/java/com/future/function/qa/steps/Scoring/QuestionBank/QuestionBankSteps.java
> +public class QuestionBankSteps extends BaseSteps {
Rename method parameter variable names for each method in this class

2019-09-16 07:19 UTC, jonathan016 commented on src/test/resources/features/QuestionBank/QuestionBank.feature
> +    And user prepare auth request
Move `And user prepare auth request` to `Background`

2019-09-16 07:19 UTC, jonathan016 commented on src/test/resources/features/QuestionBank/QuestionBank.feature
> +    And question bank error response has key "description" and value "NotBlank"
Add `And user hit logout endpoint` after this line (think as teardown) for this scenario, so the login data is not persisted in other scenarios (due to use of autowired).

Some feature files still do not use this, but in future tests will be corrected

2019-09-16 07:19 UTC, jonathan016 commented on src/test/resources/features/QuestionBank/QuestionBank.feature
> +    And question bank response data has id that should not be blank or null
Add `And user hit logout endpoint` after this line (think as teardown) for this scenario, so the login data is not persisted in other scenarios (due to use of autowired).

Some feature files still do not use this, but in future tests will be corrected

2019-09-16 07:19 UTC, jonathan016 commented on src/main/java/com/future/function/qa/api/question_bank/QuestionBankAPI.java
> +        () -> createWithCookie(request, cookie),
Return `Supplier<Response>` as other API classes do

2019-09-21 04:04 UTC, jonathan016 commented
Any update on this? cc @oliverrsebastian

2019-10-06 05:10 UTC, karnandohuang approved these changes

2020-01-28 10:47 UTC, oliverrsebastian commented
SOLVED on PR #98

2020-01-28 10:47 UTC, closed without merging